# Generated by Django 4.0.4 on 2022-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=150)),
                ('Llantas', models.DecimalField(decimal_places=8, default=0.0, help_text='esto es son llantas', max_digits=20)),
                ('Puertas', models.DecimalField(decimal_places=8, default=0.0, help_text='esto son puertas', max_digits=20)),
                ('Fechacompra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
