# Generated by Django 4.0.5 on 2022-06-02 21:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40)),
                ('Father', models.CharField(blank=True, max_length=40)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Icon', models.CharField(blank=True, max_length=50)),
                ('Url', models.CharField(blank=True, max_length=70)),
                ('SubItem', models.BooleanField(default=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permissions',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PermissionsRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Read', models.BooleanField(default=False)),
                ('Update', models.BooleanField(default=False)),
                ('Delete', models.BooleanField(default=False)),
                ('Create', models.BooleanField(default=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Deleted', models.BooleanField(default=False)),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PermissionPermissionRoles', to='authentication.permissions')),
            ],
            options={
                'verbose_name': 'Permission Role',
                'verbose_name_plural': 'Permissions Roles',
                'db_table': 'PermissionsRoles',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('Deleted', models.BooleanField(default=False)),
                ('Permissions', models.ManyToManyField(related_name='PermissionsRoles', through='authentication.PermissionsRoles', to='authentication.permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Roles', models.ManyToManyField(to='authentication.roles')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'ordering': ['pk'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='permissionsroles',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolePermissionRoles', to='authentication.roles'),
        ),
    ]
