# Generated by Django 3.2.8 on 2021-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles_api', '0005_auto_20211021_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(max_length=250),
        ),
    ]
