# Generated by Django 3.2.8 on 2021-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles_api', '0006_alter_profilefeeditem_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(max_length=255),
        ),
    ]
