# Generated by Django 4.0.4 on 2022-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelRelacion', '0002_alter_membership_invite_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_length', models.IntegerField()),
            ],
        ),
    ]
