# Generated by Django 4.0.4 on 2022-05-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_encargado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encargado',
        ),
    ]
