# Generated by Django 4.0.4 on 2022-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldemo', '0004_student'),
        ('quickstart', '0003_delete_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=128)),
                ('user', models.ManyToManyField(to='modeldemo.person')),
            ],
        ),
    ]
