# Generated by Django 4.0.4 on 2022-05-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_rename_name_encargado_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encargado',
        ),
    ]
