# Generated by Django 4.0.4 on 2022-05-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelRelacion', '0002_alter_membership_invite_reason'),
        ('quickstart', '0008_delete_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelRelacion.person')),
            ],
        ),
    ]
