# Generated by Django 4.0.4 on 2022-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelRelacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(max_length=200),
        ),
    ]
