# Generated by Django 4.0.4 on 2022-05-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelRelacion', '0003_ox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ox',
            options={'ordering': ['horn_length'], 'verbose_name_plural': 'oxenn'},
        ),
    ]
