# Generated by Django 4.0.4 on 2022-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldemo', '0004_student'),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encargado', models.ManyToManyField(to='modeldemo.person')),
            ],
        ),
    ]
