# Generated by Django 4.0.4 on 2022-05-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_rename_names_encargado_name_alter_encargado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='user',
        ),
    ]
