# Generated by Django 4.0.4 on 2022-05-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_remove_encargado_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='name',
            new_name='user',
        ),
    ]
