# Generated by Django 3.1.3 on 2020-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='categ',
            field=models.ManyToManyField(to='erp.Category'),
        ),
    ]
