# Generated by Django 4.0.4 on 2022-05-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelAnulacionMetodos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog1',
        ),
    ]
