# Generated by Django 4.0.4 on 2022-05-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelAnulacionMetodos', '0002_rename_blog_blog1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog1',
            new_name='Blog',
        ),
    ]
