# Generated by Django 3.1.3 on 2020-11-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201123_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
